In [27]:
import seaborn as sns
import pandas as pd
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

In [28]:
titanic = sns.load_dataset('titanic')
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [29]:
# Missing values
print(titanic.isna().sum())

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [30]:
data = titanic[['age', 'fare', 'pclass', 'sex']]
data=pd.get_dummies(data,drop_first=True)
data.head()

    age     fare  pclass  sex_male
0  22.0   7.2500       3      True
1  38.0  71.2833       1     False
2  26.0   7.9250       3     False
3  35.0  53.1000       1     False
4  35.0   8.0500       3      True

In [31]:
imputer = IterativeImputer(max_iter=10, random_state=0)

In [32]:
data_imputed = pd.DataFrame(imputer.fit_transform(data), columns=data.columns)

In [33]:
print("Datos Originales")
print(data.head(10))
print("Datos imputados")
print(data_imputed.head(10))

Datos Originales
    age     fare  pclass  sex_male
0  22.0   7.2500       3      True
1  38.0  71.2833       1     False
2  26.0   7.9250       3     False
3  35.0  53.1000       1     False
4  35.0   8.0500       3      True
5   NaN   8.4583       3      True
6  54.0  51.8625       1      True
7   2.0  21.0750       3      True
8  27.0  11.1333       3     False
9  14.0  30.0708       2     False
Datos imputados
         age     fare  pclass  sex_male
0  22.000000   7.2500     3.0       1.0
1  38.000000  71.2833     1.0       0.0
2  26.000000   7.9250     3.0       0.0
3  35.000000  53.1000     1.0       0.0
4  35.000000   8.0500     3.0       1.0
5  26.082704   8.4583     3.0       1.0
6  54.000000  51.8625     1.0       1.0
7   2.000000  21.0750     3.0       1.0
8  27.000000  11.1333     3.0       0.0
9  14.000000  30.0708     2.0       0.0